all:
	clang++ -std=c++14 test1.cpp -o test1 -Wall -O3
	clang++ -std=c++14 test2.cpp -o test2 -Wall -O3

debug:
	clang++ -std=c++14 test1.cpp -o test1 -Wall -g
	clang++ -std=c++14 test2.cpp -o test2 -Wall -g

clean:
	rm test1

