/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_diegofps_android_andwup_models_Wisard */

#ifndef _Included_com_github_diegofps_android_andwup_models_Wisard
#define _Included_com_github_diegofps_android_andwup_models_Wisard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_diegofps_android_andwup_models_Wisard
 * Method:    native_create
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_github_diegofps_android_andwup_models_Wisard_native_1create__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_diegofps_android_andwup_models_Wisard
 * Method:    native_create
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_com_github_diegofps_android_andwup_models_Wisard_native_1create__III
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_github_diegofps_android_andwup_models_Wisard
 * Method:    native_create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_github_diegofps_android_andwup_models_Wisard_native_1create__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_github_diegofps_android_andwup_models_Wisard
 * Method:    native_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_diegofps_android_andwup_models_Wisard_native_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_diegofps_android_andwup_models_Wisard
 * Method:    native_exportTo
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_diegofps_android_andwup_models_Wisard_native_1exportTo
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_github_diegofps_android_andwup_models_Wisard
 * Method:    native_classes
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_diegofps_android_andwup_models_Wisard_native_1classes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_diegofps_android_andwup_models_Wisard
 * Method:    native_ramBits
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_diegofps_android_andwup_models_Wisard_native_1ramBits
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_diegofps_android_andwup_models_Wisard
 * Method:    native_inputBits
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_diegofps_android_andwup_models_Wisard_native_1inputBits
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_diegofps_android_andwup_models_Wisard
 * Method:    native_learn
 * Signature: (J[II)V
 */
JNIEXPORT void JNICALL Java_com_github_diegofps_android_andwup_models_Wisard_native_1learn
  (JNIEnv *, jclass, jlong, jintArray, jint);

/*
 * Class:     com_github_diegofps_android_andwup_models_Wisard
 * Method:    native_forget
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_github_diegofps_android_andwup_models_Wisard_native_1forget
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_diegofps_android_andwup_models_Wisard
 * Method:    native_readCounts
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_com_github_diegofps_android_andwup_models_Wisard_native_1readCounts
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     com_github_diegofps_android_andwup_models_Wisard
 * Method:    native_readBleaching
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_com_github_diegofps_android_andwup_models_Wisard_native_1readBleaching__J_3I
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     com_github_diegofps_android_andwup_models_Wisard
 * Method:    native_readBleaching
 * Signature: (J[IIF)I
 */
JNIEXPORT jint JNICALL Java_com_github_diegofps_android_andwup_models_Wisard_native_1readBleaching__J_3IIF
  (JNIEnv *, jclass, jlong, jintArray, jint, jfloat);

/*
 * Class:     com_github_diegofps_android_andwup_models_Wisard
 * Method:    native_readBinary
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_com_github_diegofps_android_andwup_models_Wisard_native_1readBinary
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     com_github_diegofps_android_andwup_models_Wisard
 * Method:    native_getConfidence
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_github_diegofps_android_andwup_models_Wisard_native_1getConfidence
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_diegofps_android_andwup_models_Wisard
 * Method:    native_getExcitation
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_com_github_diegofps_android_andwup_models_Wisard_native_1getExcitation
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_diegofps_android_andwup_models_Wisard
 * Method:    native_getFirstBestPrediction
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_diegofps_android_andwup_models_Wisard_native_1getFirstBestPrediction
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_diegofps_android_andwup_models_Wisard
 * Method:    native_getSecondBestPrediction
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_diegofps_android_andwup_models_Wisard_native_1getSecondBestPrediction
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_diegofps_android_andwup_models_Wisard
 * Method:    native_getThirdBestPrediction
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_diegofps_android_andwup_models_Wisard_native_1getThirdBestPrediction
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
